### ISSUE TITLE
[Docker] Default values for environment variables/values cannot be handled if they include single/double quotes

### ISSUE THREAD

**Issue by ToshY** [MDeLuise/plant-it#302]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

Instead of passing a direct `server.env`, it's possible to only pass the environment variables that the container needs by using `environment`. But, it's also possible to fallback on a default value using the syntax `${VALUE:-fallback}`.

Let's say you have the following in your `plant-it` service.

```yaml
services:
  plant-it:
    image: ghcr.io/mdeluise/plant-it-server:${PLANT_IT_IMAGE_VERSION:-latest}
    environment:
      USERS_LIMIT: ${USERS_LIMIT:-'-1'}
```

Then this fails, giving the error:

```shell
 Failed to convert value of type 'java.lang.String' to required type 'int'; For input string: "'-1'"
```

`$ docker compose logs -ft plant-it`

```shell
plant-it-1  | 2024-08-31T13:11:11.578730831Z Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
plant-it-1  | 2024-08-31T13:11:11.598994454Z 2024-08-31T13:11:11.595Z ERROR 25 --- [           main] o.s.boot.SpringApplication               : Application run failed
plant-it-1  | 2024-08-31T13:11:11.599019882Z
plant-it-1  | 2024-08-31T13:11:11.599023288Z org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authController' defined in URL [jar:file:/opt/app/backend/app.jar!/BOOT-INF/classes!/com/github/mdeluise/plantit/authentication/AuthController.class]: Unsatisfied dependency expressed through constructor parameter 3: Failed to convert value of type 'java.lang.String' to required type 'int'; For input string: "'-1'"
plant-it-1  | 2024-08-31T13:11:11.599027176Z    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599030442Z    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599043957Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1344) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599050009Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1188) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599053395Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599070988Z    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599074044Z    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599076919Z    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599079895Z    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599083531Z    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599086437Z    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599089352Z    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599094001Z    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599096846Z    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.1.jar!/:3.0.1]
plant-it-1  | 2024-08-31T13:11:11.599099712Z    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.1.jar!/:3.0.1]
plant-it-1  | 2024-08-31T13:11:11.599102527Z    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.1.jar!/:3.0.1]
plant-it-1  | 2024-08-31T13:11:11.599105362Z    at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.1.jar!/:3.0.1]
plant-it-1  | 2024-08-31T13:11:11.599108147Z    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.1.jar!/:3.0.1]
plant-it-1  | 2024-08-31T13:11:11.599110933Z    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.1.jar!/:3.0.1]
plant-it-1  | 2024-08-31T13:11:11.599113728Z    at com.github.mdeluise.plantit.Application.main(Application.java:9) ~[classes!/:0.9.0]
plant-it-1  | 2024-08-31T13:11:11.599116483Z    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
plant-it-1  | 2024-08-31T13:11:11.599119288Z    at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
plant-it-1  | 2024-08-31T13:11:11.599122023Z    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:0.9.0]
plant-it-1  | 2024-08-31T13:11:11.599124829Z    at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[app.jar:0.9.0]
plant-it-1  | 2024-08-31T13:11:11.599127594Z    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:0.9.0]
plant-it-1  | 2024-08-31T13:11:11.599130359Z    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[app.jar:0.9.0]
plant-it-1  | 2024-08-31T13:11:11.599189340Z Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; For input string: "'-1'"
plant-it-1  | 2024-08-31T13:11:11.599194810Z    at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:79) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599197805Z    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599200741Z    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599203646Z    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599206552Z    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599209467Z    ... 25 common frames omitted
plant-it-1  | 2024-08-31T13:11:11.599212212Z Caused by: java.lang.NumberFormatException: For input string: "'-1'"
plant-it-1  | 2024-08-31T13:11:11.599215028Z    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[na:na]
plant-it-1  | 2024-08-31T13:11:11.599217843Z    at java.base/java.lang.Integer.parseInt(Integer.java:648) ~[na:na]
plant-it-1  | 2024-08-31T13:11:11.599220598Z    at java.base/java.lang.Integer.valueOf(Integer.java:989) ~[na:na]
plant-it-1  | 2024-08-31T13:11:11.599223363Z    at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:203) ~[spring-core-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599226209Z    at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:115) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599229124Z    at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:429) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599238842Z    at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:402) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599241848Z    at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599244693Z    at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73) ~[spring-beans-6.0.3.jar!/:6.0.3]
plant-it-1  | 2024-08-31T13:11:11.599247549Z    ... 29 common frames omitted
```

**Comment by ToshY** [comment]
I'll adapt and remove all quotes in the YAML config as default values. Think application still should be able to handle this.
